server:
  port: ${PORT:0}

spring:
  application:
    name: api-series
  mongodb:
    embedded:
      version: 3.6.0
  data:
    mongodb:
      database: test
      port: 27017

info:
  application:
    name: api-series

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/